Draft: Support precompiled library binaries
gdesmott/system-deps pull request #116
Opened 2024-11-14 19:39 UTC by eerii

**This is a work in progress and there are still open questions.**

This PR attempts to support precompiled binaries for libraries. Projects using `system-deps` will be able to specify an url[^1] for downloading and unpacking an archive containing static libraries and `pkg-config` descriptions. Its paths are added to the `PKG_CONFIG_PATH` for each library. This makes it possible to use projects with `-sys` crate dependencies without having to install system dependencies.

## Usage example

Before going into the technical explanation, here is a brief example on how the proposed configuration could work. We have a project `P` that depends on the crate `A`, a safe wrapper for the bindings of `liba`, in crate `A_sys`. Then, `A` depends on `B`, similarly a wrapper around `B_sys`.

```mermaid
flowchart LR
    P --> A
    A --> As{{_A_sys_}}
    A --> B
    B --> Bs{{_B_sys_}}
```

To use prebuilt binaries for `B_sys`, we can add it in the same place we configure the `system_deps` metadata.

<table>
<tr>
<td> P/Cargo.toml </td> <td> A/Cargo.toml </td> <td> B/Cargo.toml </td> <td> B/sys/Cargo.toml </td>
</tr>
<tr>
<td>

```toml
[package]
name = "P"

[dependencies]
A = { ... }
```

</td>
<td>

```toml
[package]
name = "A"

[dependencies]
A_sys = { ... }
B = { ... }
```

</td>
<td>

```toml
[package]
name = "B"

[dependencies]
B_sys = { ... }
```

</td>
<td>

```toml
[package]
name = "B_sys"

[build-dependencies]
system-deps = "7"

[features]
binary = [ "system-deps/binary" ]

[package.metadata.system-deps.B]
name = "libb"
version = "1.0"
url = "https://download/libb.tar.gz"
checksum = "..."
pkg_paths = [ "lib/pkgconfig" ]
```

</td>
</tr>
</table>

When building `P`, `libb.tar.gz` will be downloaded. To find `libb`, `system-deps` will instruct `pkg-config` to look first at `DOWNLOAD_DIR/B/lib/pkgconfig`, and if there is a valid library it will be linked. Users of `P` don't have to install `libb`.

Let's say that `A_sys` also has available binaries. The configuration is the same as before. However, imagine that the `A_sys` download already includes a version of `libb` and we want to use that instead. We can make `B_sys` use it like so:

```toml
[package]
name = "A_sys"

[package.metadata.system-deps.A]
name = "liba"
version = "1.0"
url = "https://download/liba.tar.gz"
checksum = "..."
pkg_paths = [ "lib/pkgconfig" ]

[package.metadata.system-deps.B]
follows = "A" # The metadata key
```

This time, `liba.tar.gz` will be downloaded and it will be used to link both `liba` and `libb`. Note that overriding options is only allowed from downstream crates, the outermost configuration will be used.

Finally, if an user building `P` wants to use a local copy of the binaries instead of the provided one, or another url, it can overwrite yet again the configuration set by `A_sys`:

```toml
[package]
name = "P"

[package.metadata.system-deps.A]
url = "file:///path/to/liba"
```

## Previous work

Some crates in the rust ecosystem already provide some similar functionality. Two of the most relevant are [`skia`](https://github.com/rust-skia/rust-skia) and [`openssl`](https://github.com/sfackler/rust-openssl), with different approaches.

- **Skia** uses [`skia-bindings`](https://github.com/rust-skia/rust-skia/tree/master/skia-bindings) to compile the source code in the CI and upload it to a release repository, with different versions for certain feature sets. For users, it first checks if there is a package that matches the version and features requested. If there is none, it falls backs to compiling the code locally.
- **OpenSSL** has a `vendored` feature to control if it should use precompiled binaries. By default it queries the system for the needed libraries, but if `vendored` is enabled it uses `openssl-src` to download and build the source code.

While these are great implementations, they are very specific to the crates they are in and they need certain prerequisites that may not work well for all libraries. For instance, they are working with a base crate with no other `-sys` dependencies that may also want binaries.

## Requisites

As `system-deps` is a general library, the proposal for using precompiled binaries needs to be as **general** as possible. The intended goal is to abstract the difficulty of managing the download and linking but still allow crates to configure when and how their binaries should be used. The only requirement is that they use `pkg-config` files.

It also needs to allow for **multiple crates** in the tree to request and link binaries, since many projects have a combination of libraries using `system-deps`. Additionally, some crates may want to share the same binary archive or may need to override the options of a dependency.

The configuration should be as **easy** as possible for the end user. Ideally, the sys crates should provide the default binary location and the projects using would be able to use it without further configuration. It needs to be possible to specify different downloads for each target and version of the library.

Extra care needs to be taken to avoid unnecessary recompilation or downloads. Using precompiled binaries is specially useful for less powerful systems since it avoid extra compute work, so it is important to optimize the solution.

## Configuration

The main issues when developing this implementation were related to dependency ordering and metadata reading. Cargo is very strict with some of its features, and communicating between crates during compilation is difficult. `system-deps` runs in the build script of the system libraries, once for each dependency that uses it in the project.

### Reuse current system

We need a way of specifying a set of attributes (url, checksum, paths, ...) for each binary archive we want to download. `system-deps` already does something similar with cargo metadata, with one caveat: It only reads the manifest of the crate that it is being compiled. For this use case this is too limiting, since it would mean that every dependency would have to specify its own binary url and that downstream projects would have no way of overriding this behaviour later. It also doesn't allow sharing binary archives across crates, since the downloads would be ran in parallel.

```mermaid
flowchart LR
    P --> A
    A --> As
    As{{_A_sys_}} --> sda[system_deps]
    sda --Read--> As
    A --> B
    B --> Bs
    Bs{{_B_sys_}} --> sdb[system_deps]
    sdb --Read--> Bs
```

### Environment variables

Using environment variables is also not enough. While we could ask the user to set overrides for certain crates (`SYSTEM_DEPS_BINARY_CRATE_NAME_URL`, `SYSTEM_DEPS_BINARY_CRATE_NAME_PKG_PATHS`, ...), this is too verbose, forces the user to add configuration, and it misses one feature: intermediate dependencies overriding their dependencies. Even if we supported adding environment in the build script (#114), we can't do that in middle crates since they are actually running a different instance of `system_deps`. 

```mermaid
flowchart LR
    P --> A
    A --> As
    As{{_A_sys_}} --> sda[system_deps]
    A --> B
    B --> Bs
    Bs{{_B_sys_}} --> sdb[system_deps]
    subgraph .
    Env(**Env**)
    end
    sda & sdb --Read--> .
    As & P -.Can't interact.-x sdb
```

### Patch dependency

A previous prototype tried to "inject" a dependency before `system-deps` ran. This was used as its configuration provider. Since we needed something that ran before _every_ `system_deps` instance, we added a dependency to `system-deps` that could be patched by the caller. This worked because it didn't break the dependency build order, but it was very hacky and it required that users added a `[patch]` pointing to the correct subcrate since that directive has to appear in the top level manifest. Additionally, this didn't allow configuration to come from multiple crates and it was not straightforward to write.

```mermaid
flowchart LR
    P --> A
    A --> As
    As{{_A_sys_}} --> sda[system_deps]
    A --> B
    B --> Bs
    Bs{{_ [...]

2024-11-15 08:32 UTC, gdesmott commented
Thanks for this very detailed proposal @eerii !

As [I said](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/608#note_2645647) I'm all in favor of having this feature as part of `system-deps` but having no experience with this kind of use cases I'd like to hear the input of my fellow GStreamer developers on the design.

cc @nirbheek @thiblahute @xclaesse @sdroege

2024-11-15 12:34 UTC, xclaesse commented
I'm not a big fan of downloading prebuilt, how do you know it's built for the right platform? OS, arch, libc, etc...

2024-11-15 14:01 UTC, eerii commented
> I'm not a big fan of downloading prebuilt, how do you know it's built for the right platform

The idea is to allow binaries to be specified using `cfg` target directives, so each platform can download an appropriate archive. I ommited it from the example for brevity.

```toml
[package.metadata.system-deps.A.'cfg(target = "...")']
url = "..."
```

If binaries are requested and there is not a prebuilt archive available for that target, we can always fall back to the default behaviour of `system-deps` and emit a warning.

> From a license POV if that tarball contains (L)GPL code you'll also have to provide script to rebuild it

That would be something that the projects creating the tarballs would have to include in them, not something `system-deps` has to manage, right? Or am I missing something.

Supporting source code downloads is easy. However, I worry that there is too much complexity on the compilation part. Projects have many differences on their build systems and prerequisites, so we would have to find a way of accounting for that. I'm all for adding it as an option, but I think having prebuilts can be very useful in some situations, specially for users with low end hardware that can't afford the compilation time.

2024-11-15 14:17 UTC, xclaesse commented
> That would be something that the projects creating the tarballs would have to include in them, not something `system-deps` has to manage, right? Or am I missing something.

That's indeed the problem of projects using this feature, not system-deps' problem. Maybe worth mentioning in system-deps doc?

> The idea is to allow binaries to be specified using `cfg` target directives, so each platform can download an appropriate archive.

Makes sense, that can at least help building for major platforms that has a prebuilt provided.

Another question: What's the expected file tree contained inside the tarball? How do you typically generate such tarball? In the GStreamer case I imagine that's going to be a sysroot generated by cerbero? If that's the case, I believe you'll have the problem that .pc files it contains won't be relocatable, that means it will have `-L` flags pointing to `/usr` instead of where you extracted the tarball. It's been a while I haven't touched cerbero, but IIRC it has a tool to rewrite .pc files to relocate them.

2024-11-15 14:20 UTC, xclaesse commented
BTW, Meson can now generate relocatable pc files, not sure cerbero uses that feature, and it won't work for non-Meson libraries anyway: https://mesonbuild.com/Pkgconfig-module.html#relocatable-pkgconfig-files.

2024-11-15 15:26 UTC, eerii commented
> Maybe worth mentioning in system-deps doc?

Yes, that is a good idea!

> What's the expected file tree contained inside the tarball?

That's what the `pkg_paths` metadata attribute is for. It is a list of folders inside the tarball in which to look for the `.pc` files. This way we don't enforce any specific structure on them. For the tests I have been doing with gstreamer I have been using this (the main one and the plugins directory):

```toml
pkg_paths = [ "lib/x86_64-linux-gnu/pkgconfig", "lib/x86_64-linux-gnu/gstreamer-1.0/pkgconfig" ]
```

> I believe you'll have the problem that .pc files it contains won't be relocatable

Another thing to make sure to specify in the docs is that this only works with relocatable `.pc` files, they need to point to relative paths inside the binary. I think cerbero already does this since looking at the tarball I built locally they do have relative paths and I didn't change any settings for that:

```pc
# lib/x86_64-linux-gnu/pkgconfig/gstreamer-1.0.pc 
prefix=${pcfiledir}/../../..
datadir=${prefix}/share
includedir=${prefix}/include
libdir=${prefix}/lib/x86_64-linux-gnu
libexecdir=${prefix}/libexec

exec_prefix=${prefix}
toolsdir=${exec_prefix}/bin
pluginsdir=${libdir}/gstreamer-1.0
girdir=${datadir}/gir-1.0
typelibdir=${libdir}/girepository-1.0
pluginscannerdir=${libexecdir}/gstreamer-1.0

Name: gstreamer-1.0
Description: Streaming media framework
Version: 1.25.0.1
Requires: glib-2.0 >=  2.64.0, gobject-2.0, gmodule-no-export-2.0, libunwind
Libs: -L${libdir} -lgstreamer-1.0 -lm -ldl -lnsl
Cflags: -I${includedir}/gstreamer-1.0 -DGST_STATIC_COMPILATION
```

2024-11-15 17:42 UTC, xclaesse commented
@eerii ok all good if cerbero uses `${pcfiledir}` already, that's what Meson does as well with `-Dpkgconfig:relocatable=true`. That just need to be documented then :)

2024-11-28 08:06 UTC, nirbheek commented
I finally had time to read through the whole proposal. It's good and seems sound. Some comments:

> Does it make sense to concatenate pkg_paths lists?

Yes. The default should be `@LIBDIR@/pkgconfig`, and the metadata can provide more. Note that @LIBDIR@ can vary per-platform, so it must not be hard-coded in the Cargo.toml, like in the examples provided above.

The way this is usually solved, is that the prebuilt prefix ships with its own pkg-config, which has a value hard-coded in it for where the pc files are. This is obviously wasteful when you're dealing with several different platforms, and might not even work when cross-compiling (the bindir will only contain host binaries, not binaries for your build machine).

There are two possible solutions:

1. Search the prebuilt prefix for `.pc` files and add all such dirs to the list of pkg_paths
2. Require prebuilt prefixes to ship with a `info.toml` file that species this
   - This can be extended for other use-cases later
   
I don't have a strong preference here.

> Does follow or url have priority?

I don't understand this question. "Outermost" values should override "inner" values.

> How to handle two crates overwriting the same dependency with conflicting values?

Throw an error and let the user deal with it. It's always better to be strict, because it's easier to allow use-cases that weren't allowed previously, than disallow use-cases that have always worked incorrectly.

2024-12-02 12:35 UTC, eerii commented
Thank you so much for the thorough comments!

> The default should be @LIBDIR@/pkgconfig

That makes sense. What I was thinking was using the same cfg directives that handle downloads for different platforms to specify the library paths for each binary:

```toml
[package.metadata.system-deps.A.'cfg(target = "linux_x86...")']
url = "linuxdownload.tar.gz"
pkg_paths = [ "linuxlib/pkg-config" ]

[package.metadata.system-deps.A.'cfg(target = "windows_x86...")']
url = "windowsdownload.tar.gz"
pkg_paths = [ "windowslib/pkg-config" ]
```

But I agree that this can quickly become too verbose and difficult to handle. Searching the prebuilt for `.pc` files sounds good, as long as the packages don't contain conflicting files. I think this is a reasonable expectation, if there are no clear use cases that require otherwise.

> I don't understand this question. "Outermost" values should override "inner" values.

Sorry, I wasn't very clear with this. But yes, the idea is that outermost values override inner ones.

> Throw an error and let the user deal with it. It's always better to be strict, because it's easier to allow use-cases that weren't allowed previously, than disallow use-cases that have always worked incorrectly.

And yes, I have been working on ensuring that this is done correctly and analyzing the different package graph cases and which are conflicting. I'm almost done fixing the implementation to account for this, I'll upload the revised version later today.

2024-12-02 21:01 UTC, nirbheek commented
> I think I prefer your approach of requiring the user to specify the paths instead of trying to guess tbh, we should also probably show that right from the start in the documentation.

I think that's a property of the prefix (and hence the tarball). It doesn't make sense to put in the configuration, and it just makes it easy to get it wrong. That's why I suggested that the prefix/tarball could specify it in a `config.toml` or something, if we don't want to do autodetection.

2024-12-02 22:54 UTC, nirbheek commented
For example, if you want to add support for a new target (say, something based on RISC-V, or NixOS), you don't need to update every -sys crate (and potentially every project that uses that -sys crate). You just build some new binary tarballs and everything works.

2024-12-03 11:57 UTC, thiblahute commented
> For example, if you want to add support for a new target (say, something based on RISC-V, or NixOS), you don't need to update every -sys crate (and potentially every project that uses that -sys crate). You just build some new binary tarballs and everything works.

You will have to anyway to add the URI to the new tarball anyway, unless we add some templating logic, which could also make sense.

> > I think I prefer your approach of requiring the user to specify the paths instead of trying to guess tbh, we should also probably show that right from the start in the documentation.
> 
> I think that's a property of the prefix (and hence the tarball). It doesn't make sense to put in the configuration, and it just makes it easy to get it wrong. That's why I suggested that the prefix/tarball could specify it in a `config.toml` or something, if we don't want to do autodetection.

That approach is fine by me, I do not like autodetection. Also it could be added later fmopv as we already have a working solution.

Also, what is the point of having the .pc files in the tarballs platform dependent? They are never meant to be used on  a system wide prefix, but should be consumed by intermediary apps. I have the impression that we could default to `lib/pkgconfig` and make it all simpler no?

2024-12-09 06:33 UTC, nirbheek commented
> You will have to anyway to add the URI to the new tarball, unless we add some templating logic, which could also make sense.

I thought that was the plan already, the manylinux URIs look templated :)

> Also, what is the point of having the .pc files in the tarballs platform dependent? They are never meant to be used on a system wide prefix, but should be consumed by intermediary apps. I have the impression that we could default to lib/pkgconfig and make it all simpler no?

That's how distros work. Libraries and executables built for a particular distro will look for that distro's' libdir in whatever prefix you use. We tried to not do this in cerbero already, and that failed.

2024-12-09 15:50 UTC, thiblahute commented
> > Also, what is the point of having the .pc files in the tarballs platform dependent? They are never meant to be used on a system wide prefix, but should be consumed by intermediary apps. I have the impression that we could default to lib/pkgconfig and make it all simpler no?
> 
> That's how distros work. Libraries and executables built for a particular distro will look for that distro's' libdir in whatever prefix you use. We tried to not do this in cerbero already, and that failed.

Interesting, how did that fail?

2024-12-09 16:12 UTC, nirbheek commented
> Interesting, how did that fail?

I don't remember anymore. Something around how modules are searched. All I remember is that in cerbero we tried to enforce `prefix/lib` everywhere and had to revert it.

2024-12-13 16:31 UTC, eerii commented
Hi! Update on this, I have been refactoring the proposal, cleaning old changes and improving the interface. I think that it is now at a point where I'm pretty happy with the public API and how the parsing system works. There may be a few details to still work on, but I think it is a good place to start reviewing this.

I improved the error handling and added tests for both the metadata parsing and the binary downloads and filetypes. Since there are complex dependency cases with multiple pacakges, each new test generates the needed `Cargo.toml` files. This makes it easier to write tests and check a few variations on each.

I updated the PR description, but here is a list of the important changes:

#### Improvements on metadata parsing

The naive previous implementation only worked for very simple package trees and it didn't fail properly on conflicts and sometimes it produced wrong results. I have reworked this part from scratch and it should hopefully be more robust and able to handle more generic cases. It is also reusable outside of `system-deps` (for example, to read `gstreamer-rs` plugins).

First, the base package(s) is read from the root manifest. For each one, we read the metadata and descend into its (unvisited) dependencies, building an "upside down" dependency tree containing the metadata. Starting from the leaves we reduce the value applying the correct overwrites and checking for conflicts. The final result is a single map with the calculated values.

It also has many little improvements, such as type checking for values, extending lists instead of overwriting them, using `cfg` to gate configurations behind a target and more. Additionally, as @nirbheek suggested, paths can be read from a `info.toml` at the base level of the downloaded archive:

```toml
# info.toml
paths = [ "lib/pkgconfig" ]
```

#### Reworked how prebuilt binaries are shared:
 
The `follows` key has been changed to `provides`. Instead of placing it on each package that wants to reuse binaries from another, the original package can have a list of what libraries are contained in the binary it is downloading. This is more concise and avoids having to modify other manifests.

```toml
# New version
[package.metadata.system-deps.gstreamer_1_0]
url = "..."
checksum = "..."
provides = [ "glib_2_0", "gobject_2_0", "gio_2_0", "gst*" ]

# Before
[package.metadata.system-deps.gstreamer_1_0]
url = "..."
checksum = "..."

[package.metadata.system-deps.glib_2_0]
follows = "gstreamer_1_0"

[package.metadata.system-deps.gobject_2_0]
follows = "gstreamer_1_0"

# Many more lines ...
```

Internally, it is actually adding the `follows` key to the packages when building the final metadata tree (this is done to reuse the same overwriting and merging rules and to ensure that there are no conflicts), so the previous version still technically works.

Additionally, **wilcards** are supported for provided packages. This is particularly useful for `gstreamer` where there are too many libraries to reliably list. It is important to note that wildcards are a bit special and they never overwrite a previous package url, as opposed to writing the full name in `provides`. There are a few technical reasons why this was kept like that, mainly code complexity and performance overhead in metadata resolution. I think they are useful but we should clearly explain how they work in the documentation.

#### Downloading and decompressing

These actions should now be faster and more reliable. They now happen in parallel and only if there wasn't a valid version. Checksums are properly calculated and checked.

The library for handling the downloads has been changed from [`reqwest`](https://crates.io/crates/reqwest) to [`attohttpc`](https://crates.io/crates/attohttpc), since it is more lightweight and it doesn't depend on an async runtime.

#### Reorganize the proposal structure

Instead of having three crates and everything all over the place, now the logic is on the `system-deps-meta` crate (gated by features) so that it can be easily reused by other projects.

- **Build** `system-deps-meta`: Finds project root.
- **Lib** `system-deps-meta`: Utils for parsing metadata and downloading binaries.
- **Build** `system-deps`: Binaries are downloaded and paths are serialized (before any dependent crate is built).
- **Lib** `system-deps`: Probe libraries, set pkg-config paths, ...

#### What's next?

The current version now finally covers the use cases indicated in the proposal, works for projects with complex dependency trees, and it has tests and error handling. There are a few details missing that are important before merging:

- Although it is somewhat complete, finish the bits of documentation left and add an example to the README.
- `system-deps` allows to specify multiple versions of a package with `[system-deps.name.version]`. At the moment the `url` can only be specified at the top level, but adding version support shouldn't be too hard.
- Up until now I have been calling these feature "binary" but I'm not too sold on the name. Other options are "prebuilt", "precompiled", "download", "vendored". What do you think we should refer to this feature as? I think it is a good idea to do a pass rewriting the docs and naming of everything to be more cohesive.

There are other features that I think are more suited to a followup PR, since this is already big enough and they are not essential:

- Unify `system-deps-meta` and `metadata.rs`. This is not hard, we could probably do it now, but it will be tricky to do without adding dependencies. I was more lenient on `system-deps-meta` since it is opt-in and it will not affect existing users, but `cargo-metadata` uses `serde-json` so we are duplicating the serialization libraries. So I think this will require more careful planning.
- Templated URIs and other similar features.
- Caching is not a big issue since `read_metadata` is only called once on the build script, which all crates then share. However, I'm sure some improvements can be made to make this even more performant.

2024-12-13 16:43 UTC, gdesmott commented
Thanks for all your work on this!

I'll let @thiblahute and @nirbheek review the design and user API as they know much more than me on this use case.

Btw, feel free to clean up the branch (squash commits, etc) as it will be required before merging.

2025-05-21 15:50 UTC, gdesmott commented
Should we go forward with this?

@nirbheek @thiblahute : I think you were interested about such feature, right?

2025-05-21 20:34 UTC, thiblahute reviewed
I had started to review that a while back and only had those comments, I wanted to have another deeper look but I don't have time right now.

I would love to see that MR finished/merged yes

2025-05-21 20:34 UTC, thiblahute commented on build.rs
> +        println!("cargo:rustc-env=BINARY_PATHS={}", dest.display());
Should `BINARY_PATHS` be namespaced?

2025-05-21 20:34 UTC, thiblahute commented on meta/src/lib.rs
> +pub const BUILD_MANIFEST: &str = env!("BUILD_MANIFEST");
Should that env var be namespaced?

2025-05-21 20:34 UTC, thiblahute commented on meta/src/lib.rs
> +pub const BUILD_TARGET_DIR: &str = env!("BUILD_TARGET_DIR");
Ideally I think all those pre built binaries should go into some user cache dir, the same way cargo does it for crate srcs. This can be added at a later stage anyway.

2025-05-22 16:07 UTC, eerii commented on build.rs
> +        println!("cargo:rustc-env=BINARY_PATHS={}", dest.display());
That's a good idea, we can prefix this variables with `SYSTEM_DEPS_` to avoid any clashes.

2025-05-22 16:10 UTC, eerii commented
I also had some cleanup changes and fixes from a while ago, let me review those and I'll update the branch c: Would also love to see this merged.

Apologies for not updating this sooner, I had to deal with some issues but everything is better now.

2026-03-16 11:41 UTC, calvaris commented
I think the this would be ready for review.

2026-03-16 12:09 UTC, gdesmott commented
Thanks @calvaris !

As said previously, I'm happy to integrate this feature but I'd rather have it reviewed by someone who will actually use it. Even better, who try to integrate it in their crate.

@thiblahute : is this something you are still interested in?

2026-03-16 12:36 UTC, eerii reviewed
Thanks :) I left some comments and questions to discuss. I would also like to rename some variables since I did a poor name with that (`l`, `n`, `c`...), but that's not as important now.

2026-03-16 12:36 UTC, eerii commented on meta/src/binary.rs
> +    /// This function may panic, but only on unrecoverable results such as downloading or
Could this be handled better? Should we treat these errors as unrecoverable? Instead of using the trait we could write a regular member that takes the binaries and returns `Result<Self, ...>`. Not sure if it is worth it though.

2026-03-16 12:36 UTC, eerii commented on meta/src/binary.rs
> +                    s.spawn(move || make_available(bin, &dst).map_err(|e| panic!("{}", e)));
Same here, a panic can crash the entire build process. Maybe we could return results and disable that specific one if they couldn't be downloaded, using the system ones as a fallback with a warning. But maybe falling back is more confusing and error prone for the end user?

2026-03-16 12:36 UTC, eerii commented on meta/src/binary.rs
> +fn find_pkgconfig_dirs(dir: &Path) -> Vec<PathBuf> {
Should this have a recursion limit to avoid hangs on very deep binaries?

Also, it might be good to avoid traversing symlinks. I don't know who would add a symlink to a binary tarball, but if there is one this could loop forever ([`is_dir`](https://doc.rust-lang.org/std/path/struct.Path.html#method.is_dir) follows symlinks).

2026-03-16 12:36 UTC, eerii commented on meta/src/binary.rs
> +    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
This would be better as a `LazyLock` but I think MSRV is 1.78 and it was introduced on 1.80.

2026-03-16 12:36 UTC, eerii commented on src/metadata.rs
> +                ("url", DeValue::String(_)) => {}
This feels like a bit of a hack, but I guess we need it since we are using two different metadata parsing systems.

2026-03-16 12:36 UTC, eerii commented on meta/src/parse.rs
> +    // NOTE: Use `extract_if` when it is available https://github.com/rust-lang/rust/issues/43244
This comment can be updated. There is [`extract_if`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.extract_if) now, but it landed in 1.87, so we can't use it until we increase the MSRV

2026-03-16 12:36 UTC, eerii commented on src/lib.rs
> +//! TODO: Complete examples
There are a few TODOs in the documentation that need to be fixed before landing.

2026-03-16 16:08 UTC, thiblahute commented
> Thanks @calvaris !
> 
> As said previously, I'm happy to integrate this feature but I'd rather have it reviewed by someone who will actually use it. Even better, who try to integrate it in their crate.
> 
> @thiblahute : is this something you are still interested in?

I sure am, I am working very closely with @calvaris on it. I already reviewed most of the code but I want all the other pieces to be ready to land to do a final review and I will let you know when I am happy with all of it.

2026-03-17 11:40 UTC, calvaris commented
I think I addressed all comments.

2026-03-17 12:17 UTC, nirbheek commented
Reading through the context, the main question I have is, have we solved the problem where to add support for a new platform, you used to need to update the Cargo.toml of all -sys dependencies. Have we moved the declaration to a template sort of thing where that wouldn't be needed?

2026-03-17 14:16 UTC, eerii commented
> Have we moved the declaration to a template sort of thing where that wouldn't be needed?

Ah thank you for bringing that up. It is quite important, yes. And it wasn't implemented yet.

I think the main problem to solve here would be related to checksums. How would we specify the checksum (or a similar way to verify the download) of each different platform. Also, even if we don't update the Cargo.toml to add new platforms, we would need to update the checksums when new versions of the binary are available. Does anyone have any idea on how to tackle this?

2026-03-18 03:53 UTC, nirbheek commented
Usually these problems are solved with a canonical registry (f.ex. Python wheels). But I don't think that's something we want to do here.

I think the simplest solution is to make it so that any metadata you provide in your Cargo.toml overrides metadata specified in dependent crates. That will allow you to:

1. Support a new platform by adding metadata for all dependencies recursively in your own Cargo.toml
2. Ship an updated binary for any indirect dependency instead of having to wait for the dependency to make a new binary release
3. Ship a "mega prefix" which contains binaries for all your dependencies tailored to your use-case, for example using a specific CRT.

Then we don't need any templating, and we don't need a registry to fetch checksums or download URLs from.

One more thing I think we should add alongside checksums, is the ability to specify a URL for PGP signatures that are downloaded and verified. We don't have to implement it in this PR, but I think we should add it to the spec at least?

Unlike sources which can be trivially inspected for tampering (just run `diff -ur`), that's not true for binaries. A binary uploaded to a server can be tampered by someone who has compromised the server. Now, this will just cause checksum errors in existing `Cargo.toml` entries, but newer entries could be compromised depending on how you get the checksum (usually in a `.sha256sum` file alongside actual file). You cannot fool PGP signatures this way, unless you can impersonate the signer.

2026-03-18 04:40 UTC, nirbheek commented
Also, I just discovered this tool: https://github.com/cargo-bins/cargo-binstall maybe something to look at for inspiration. It can download binaries "automatically" for some crates.

2026-03-18 10:52 UTC, calvaris commented
We've implemented URL template support for platform management in this branch, so a single URL entry can cover multiple platforms. Regarding metadata overrides and PGP signatures, these are both great ideas, but I think they're out of scope for this PR. We can spec them out and implement them in follow-up PRs.

2026-03-18 10:56 UTC, nirbheek commented
Metadata override was meant to be a solution for the problem of specifying checksums in all -sys crates despite having URL templates 🙂 

But as you wish!

2026-04-09 12:54 UTC, calvaris commented
In this new version I added support for Mac and Windows and addressed the comments, at least most of them.

2026-04-09 13:54 UTC, eerii reviewed
Looks good! :)

2026-04-09 13:54 UTC, eerii commented on build.rs
> +}
```suggestion
pub fn main() -> Result<(), Box<dyn std::error::Error>> {
    #[cfg(feature = "binary")]
    binary::build()?;
    Ok(())
}
```

2026-04-09 13:54 UTC, eerii commented on build.rs
> +                let joined = dirs.join(";");
Maybe it's better to use [`std::env::join_paths`](https://doc.rust-lang.org/std/env/fn.join_paths.html)? I think just joining them could fail in some cases.

2026-04-09 13:54 UTC, eerii commented on src/metadata.rs
> +                ("url", DeValue::String(_)) => {}
```suggestion
				// Fields used by system-deps-meta
                ("url", DeValue::String(_)) => {}
```

2026-04-09 13:54 UTC, eerii commented on meta/src/error.rs
> +
```suggestion

impl std::error::Error for Error {}

```

2026-04-09 13:54 UTC, eerii commented on meta/src/error.rs
> +            Self::Binary(e) => e.fmt(f),
```suggestion
            Self::CfgNotObject(expr) => {
                write!(f, "The expression '{}' is not guarding a package", expr)
            }
            Self::DeserializeError(e) => write!(f, "Error while parsing: {}", e),
            Self::IncompatibleMerge => write!(f, "Can't merge metadata"),
            Self::PackageNotFound(pkg) => write!(f, "Package not found: {}", pkg),
            Self::SerializeError(e) => write!(f, "Error while parsing: {}", e),
            Self::InvalidCfg(e) => write!(f, "Invalid cfg() expression: {}", e),
            Self::UnsupportedCfg(expr) => {
                write!(f, "Unsupported cfg() expression: {}", expr)
            }
            #[cfg(feature = "binary")]
            Self::Binary(e) => e.fmt(f),
```

2026-04-09 13:54 UTC, eerii commented on meta/src/error.rs
> +                }
```suggestion
                Self::DecompressError(e) => {
                    write!(f, "Failed to decompress the binary archive: {}", e)
                }
                Self::DirectoryIsFile(path) => {
                    write!(f, "The binary target directory is a file: {}", path)
                }
                Self::DownloadError(e) => write!(f, "Failed to download binary archive: {}", e),
                Self::InvalidChecksum(pkg, specified, calculated) => {
                    write!(
                        f,
                        "Mismatch in the checksum of {}:\n\
                        - Specified: {}\n\
                        - Calculated: {}",
                        pkg, specified, calculated
                    )
                }
                Self::InvalidDirectory(e) => {
                    write!(f, "The binary target directory is not valid: {}", e)
                }
                Self::InvalidFollows(pkg, follows) => {
                    write!(f, "The package {} follows {}, which doesn't exist", pkg, follows)
                }
                Self::LocalFileError(e) => {
                    write!(f, "The requested local folder could not be read: {}", e)
                }
                Self::SymlinkError(e) => {
                    write!(f, "Couldn't create symlink to local binary folder: {}", e)
                }
                Self::UnsupportedExtension(ext) => {
                    write!(f, "Unsupported binary extension: {}", ext)
                }
```

2026-04-09 13:54 UTC, eerii commented on meta/build.rs
> +fn find_with_cargo(dir: &Path) -> Option<PathBuf> {
Hmm interesting, I didn't know about the deadlock behaviour on Windows. Let's call this `find_workspace_root` as well, they are mutually exclusive and that way we don't have to do the `cfg` below.

```suggestion
fn find_workspace_root(dir: &Path) -> Option<PathBuf> {
```

2026-04-09 13:54 UTC, eerii commented on meta/build.rs
> +    let result = find_workspace_root(&dir);
Then this can just be:

```suggestion
    let result = find_workspace_root(&dir);
```

2026-04-09 13:54 UTC, eerii commented on src/test_binary.rs
> +
```suggestion
```

There is already a test below, even if it is disabled.

2026-04-09 13:54 UTC, eerii commented on src/lib.rs
> +//! binary url (for example, for local testing).
Do we still needd this?

2026-04-09 13:54 UTC, eerii commented on src/lib.rs
> +        env::join_paths(iter::once(self.as_ref()).chain(other)).unwrap()
```suggestion
        env::join_paths(iter::once(self.as_ref()).chain(other))
            .expect("Path contains invalid character")
```

2026-04-09 13:54 UTC, eerii commented on src/lib.rs
> +        env::join_paths(slice.iter().map(|p| p.as_ref()).chain(other)).unwrap()
```suggestion
        env::join_paths(slice.iter().map(|p| p.as_ref()).chain(other))
            .expect("Path contains invalid character")
```

2026-04-09 13:54 UTC, eerii commented on src/lib.rs
> +            None => env::join_paths(other.as_ref().iter().map(|p| p.as_os_str())).unwrap(),
```suggestion
            None => env::join_paths(other.as_ref().iter().map(|p| p.as_os_str()))
                .expect("Path contains invalid character"),
```

2026-04-09 13:54 UTC, eerii commented on meta/src/parse.rs
> +fn collect_nodes(manifest: &Path, section: &str) -> Result<HashMap<String, MetadataNode>, Error> {
Is there an issue for this and the `locate-project` behaviour on Windows that we can link?

Since we already have to rebuild the metadata parser we might as well remove the `cargo_metadata` dependency completely. But I'd say let's do that in a followup patch. The metadata parser was always intended to be temporary and replaced by an extension of the `src/metadata.rs` that we already had. I think it will be *much* easier to do that refactor once this huge PR is merged.

2026-04-09 13:54 UTC, eerii commented on meta/src/binary.rs
> +        }
```suggestion
        let extension = path
           .extension()
           .and_then(|s| s.to_str())
           .unwrap_or("<error>");
        match extension {
            #[cfg(feature = "pkg")]
            "pkg" => Ok(Extension::Pkg),
            #[cfg(feature = "nsis")]
            "exe" => Ok(Extension::Nsis),
            #[cfg(feature = "gz")]
            "gz" | "tgz" => Ok(Extension::TarGz),
            #[cfg(feature = "xz")]
            "xz" => Ok(Extension::TarXz),
            #[cfg(feature = "zip")]
            "zip" => Ok(Extension::Zip),
            e => Err(BinaryError::UnsupportedExtension(e.into())),
        }
```

2026-04-09 13:54 UTC, eerii commented on meta/src/binary.rs
> +            let Ok(meta) = entry.metadata() else {
```suggestion
            let Ok(meta) = entry.symlink_metadata() else {
```

I'm not sure if this is fixing the symlink issue. [`is_dir`](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.is_dir) says it will be false for symlink metadata obtained from [symlink_metadata](https://doc.rust-lang.org/std/fs/fn.symlink_metadata.html), but we aren't using that function. I think we may want to call that instead.

2026-04-09 13:54 UTC, eerii commented on meta/src/binary.rs
> +    while let Some((current, depth)) = queue.pop() {
```suggestion
    let mut stack = vec![(dir.to_path_buf(), 0usize)];
    while let Some((current, depth)) = stack.pop() {
```

Small naming nit, but this is LIFO, not FIFO

2026-04-09 13:54 UTC, eerii commented on meta/src/binary.rs
> +                    queue.push((path, depth + 1));
```suggestion
                    stack.push((path, depth + 1));
```

2026-04-09 22:11 UTC, thiblahute requested changes
I didn't review it all, but I think it looks good apart from the windows nsis feature we need to clean up.

2026-04-09 22:11 UTC, thiblahute commented on meta/Cargo.toml
> +pkg-extractor = { git = "https://github.com/thiblahute/pkg_extractor", optional = true }
You should use the release I just published here: https://crates.io/crates/pkg-extractor/0.1.1 now :-)

2026-04-09 22:11 UTC, thiblahute commented on meta/src/binary.rs
> +        }
``` 
-            .unwrap_or("<error>");
+           .unwrap_or("<none>");
```

2026-04-09 22:11 UTC, thiblahute commented on meta/src/binary.rs
> +    /// package config files. These directories will be prepended to the `PKG_CONFIG_PATH` when
```suggestion
    /// package config files (`.pc`). These directories will be prepended to the `PKG_CONFIG_PATH` when
```

2026-04-09 22:11 UTC, thiblahute commented on meta/src/binary.rs
> +/// Search for an existing GStreamer NSIS installation on Windows.
That whole GStreamer specific logic doesn't belong here at all, we need to think about it again, but that whole nsis feature seems weird to me and I have the impression we should simply extract the .exe ourself in the right place and use that instead.

2026-04-10 08:04 UTC, calvaris commented on meta/src/binary.rs
> +                    s.spawn(move || make_available(bin, &dst).map_err(|e| panic!("{}", e)));
I wouldn't fallback to the system. It's quite misleading.

2026-04-17 08:19 UTC, calvaris commented on meta/src/lib.rs
> +pub const BUILD_TARGET_DIR: &str = env!("BUILD_TARGET_DIR");
We have a TODO for this.

2026-04-17 08:28 UTC, calvaris commented on meta/src/parse.rs
> +fn collect_nodes(manifest: &Path, section: &str) -> Result<HashMap<String, MetadataNode>, Error> {
Ok, let's do it in a follow up then.

2026-04-17 08:32 UTC, calvaris commented on meta/src/binary.rs
> +/// Search for an existing GStreamer NSIS installation on Windows.
We moved to inno. This should be done.

2026-04-17 08:33 UTC, calvaris commented on meta/Cargo.toml
> +pkg-extractor = { git = "https://github.com/thiblahute/pkg_extractor", optional = true }
This is left as it is because of the lzma rework.

2026-04-17 08:38 UTC, calvaris commented on meta/src/binary.rs
> +        }
Will be solved in next push

2026-04-17 08:39 UTC, calvaris commented on meta/src/binary.rs
> +    /// package config files. These directories will be prepended to the `PKG_CONFIG_PATH` when
Will be solved in next push

2026-04-27 11:15 UTC, nirbheek commented
@thiblahute I would **strongly** recommend using a pkg-config in the downloaded prefix if available over anything on the system.

1. People often have random broken pkg-config implementations scattered around in their PATH on Windows
2. pkg-config can be built with options that can break things, for example by inserting "system" includedirs and libdirs, or for auto-detecting the prefix

So there is no guarantee that you can consume the gstreamer binaries with any pkg-config other than what we ship in the installer / tarball.

2026-04-28 05:58 UTC, jschwe commented
> Build scripts get passed one argument that can be read using std::env::args. This points to the build directory they have assigned in the root target directory. This can be different than reading OUT_DIR, which is a target directory in the folder where the dependency is cloned (/project/dir/target vs .cargo/checkout/dep/target). Because that directory is inside the project, we can run cargo locate-project to get the workspace root, which contains the top level Cargo.toml manifest. 

Note that users can set [`CARGO_TARGET_DIR`](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir) to an arbitrary directory, which would break this approach. Having a global target dir is apparently not that uncommon, to cache compilation results (see also next link).
How does this interact with the [Cargo cross workspace cache project goal for 2026](https://rust-lang.github.io/rust-project-goals/2026/cargo-cross-workspace-cache.html)? 

On a different note, I'm curious if this proposal would also work for prebuilt shared libraries? Rebuild times can be dominated by link times, and having a shared library would help reduce that (at the cost that the user needs some additional configuration on their side, but for many projects that might be a tradeoff worth making for larger libraries).

2026-04-28 06:04 UTC, nirbheek commented
> On a different note, I'm curious if this proposal would also work for prebuilt shared libraries

The primary target here is prebuilt shared libraries, which is the only thing supported by GStreamer via Cerbero on Windows (for now — you can always build gstreamer with static libs yourself from source), and the preferred configuration on macOS and Linux.

2026-04-28 07:36 UTC, eerii commented
> Note that users can set [`CARGO_TARGET_DIR`](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir) to an arbitrary directory, which would break this approach. Having a global target dir is apparently not that uncommon, to cache compilation results (see also next link).

Yes, this is a limitation. Unfortunately I don't think there is a better way of reliably finding the main `Cargo.toml` yet. So as of now this is a best effort approach. See https://github.com/rust-lang/cargo/issues/3946.

As a workaround for those tricky cases, users can set the `SYSTEM_DEPS_BUILD_MANIFEST` var to point to it. If it can't be found, we print a warning [here](https://github.com/gdesmott/system-deps/pull/116/changes#diff-4b956f1bb16a0d8cc6f4003775399febb100497f08cd7a82e722825f2dfb44d2R79) to let users know what to do:

> Error determining the cargo root manifest.
> Please set `SYSTEM_DEPS_BUILD_MANIFEST` to the path of your project's Cargo.toml.

2026-05-26 19:31 UTC, thiblahute commented on meta/src/binary.rs
> +        let dst_str = dst.to_string_lossy().replace('/', "\\");
Isn't there a better API for that?

2026-05-26 19:31 UTC, thiblahute commented on meta/src/binary.rs
> +#[cfg(windows)]
Can't we move that workaround to gstreamer-rs build.rs file directly by any chance?

2026-05-28 12:19 UTC, calvaris commented on meta/src/binary.rs
> +#[cfg(windows)]
I'd rather keep it here. Extraction is owned by system-deps-meta, not by gstreamer-rs: the rewrite has to run inside make_available, after decompression and before any sys-crate's build.rs probes the bundle with pkg-config — and cargo gives us no deterministic ordering between sibling sys-crates, so moving the patch into gstreamer-rs would force every one of them (gstreamer-sys, gstreamer-base-sys, gstreamer-video-sys, …) to synchronise on it. The bug isn't GStreamer-specific either: any bundle distributed via the binary feature whose .pc files live in nested subdirectories (lib/<something>/pkgconfig/foo.pc) trips pkg-config 0.29.2's --define-prefix heuristic on Windows, so keeping the fix here avoids every future consumer of system-deps binary having to re-implement it. It also keeps the rewrite where it semantically belongs — mutating files under <TARGET_DIR>/<name>/, a directory wholly owned by system-deps-meta and not visible to gstreamer-rs except via the public Paths API. Finally, the doc comment already flags this as a self-deprecating workaround: once the GStreamer Windows installer ships pkgconf (the modern fork without this bug) instead of pkg-config 0.29.2, the whole function goes away.

2026-05-28 12:23 UTC, nirbheek commented on meta/src/binary.rs
> +#[cfg(windows)]
We build our own pkg-config in cerbero, so we can fix the bug in pkg-config too: https://gitlab.freedesktop.org/gstreamer/meson-ports/pkg-config

2026-05-28 12:28 UTC, nirbheek commented on meta/src/binary.rs
> +#[cfg(windows)]
Actually, another thing: we're not supposed to use --define-prefix with pkg-config anymore in Cerbero. All pc files have a relative prefix defined: `prefix=${pcfiledir}/../..` or `prefix=${pcfiledir}/../../..` (for plugins). I am surprised that you are running into this bug at all.

2026-05-28 12:32 UTC, nirbheek commented on meta/src/binary.rs
> +#[cfg(windows)]
https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/2257

2026-06-01 10:36 UTC, calvaris commented on meta/src/binary.rs
> +#[cfg(windows)]
Nice, I guess we can wait and once this is done I'll update the PR. I just uploaded a version still with this workaround.

2026-06-01 13:34 UTC, nirbheek commented on meta/src/binary.rs
> +#[cfg(windows)]
It has already been merged and backported. It will be in 1.28.4, so you could wait for that perhaps.

2026-06-01 20:23 UTC, thiblahute commented on meta/src/binary.rs
> +#[cfg(windows)]
Is there a build @calvaris can try with?

2026-06-02 04:51 UTC, calvaris commented on meta/src/binary.rs
> +#[cfg(windows)]
If someone presses play and generate the artifacts in the MR, yes.

2026-06-09 10:22 UTC, calvaris commented on meta/src/binary.rs
> +#[cfg(windows)]
@nirbheek , just filed https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/2264 to solve a linking issue in servo

2026-06-10 16:41 UTC, calvaris commented on meta/src/binary.rs
> +#[cfg(windows)]
As we discussed on Matrix, I did the changes you asked for. All seems to check out including servo.

2026-06-19 10:25 UTC, thiblahute commented
@gdesmott I think this is ready now. The only thing that I think is missing (not sure if it is blocking the merge) is a release of [inno](https://github.com/russellbanks/inno).

2026-06-19 14:33 UTC, eerii reviewed
Looks good to me too. Would we need a `pkg-extractor` release too?

2026-06-22 07:01 UTC, gdesmott commented
Ideally yes, I'd rather not depend on unreleased deps.

2026-06-22 11:47 UTC, thiblahute commented
> Looks good to me too. Would we need a `pkg-extractor` release too?

That one is done, we are only missing a release of [inno](https://github.com/russellbanks/inno/)

2026-06-22 11:54 UTC, gdesmott commented
Also, before merging them I'd like to add one of you as co-maintainer.
I'm not gonna use this feature so want to ensure we have some who do to help maintaining it.

@thiblahute : would you be interested ?

2026-06-22 11:56 UTC, thiblahute commented
Sure, I can do that.

2026-07-14 08:41 UTC, gdesmott commented on meta/Cargo.toml
> +[dependencies]
Can we centralize all the deps in the workspace `Cargo.toml`?
I find it more convenient.

2026-07-15 12:10 UTC, calvaris commented
I think this is ready. I tested it with gstreamer-rs and servo.

2026-07-15 12:14 UTC, gdesmott commented
Looks like clippy CI is failing: https://github.com/gdesmott/system-deps/actions/runs/29391981683/job/87283711464?pr=116

Once CI is all green, I'm happy to merge this once @thiblahute approved.

2026-07-15 15:36 UTC, thiblahute commented
Let's get it in I would say

2026-07-16 05:48 UTC, merged

2026-07-16 06:22 UTC, gdesmott commented
I just released `8.0.0` with this feature.

Thanks a lot to you all for making it happen! :+1: